import React, { createContext, useState, useContext, useMemo, useEffect } from 'react';

const translations = {
  en: {
    home: "Home",
    products: "Products",
    admin: "Admin",
    cart: "Cart",
    welcomeTitle: "Welcome to ZShop",
    welcomeSlogan: "Your Gateway to Unrivaled Luxury and Exceptional Quality.",
    exploreCollections: "Explore Our Collections",
    whyChooseUs: "Why Choose ZShop?",
    unwaveringSecurity: "Unwavering Security",
    securityDesc: "Your peace of mind is our priority. We utilize cutting-edge encryption and robust security protocols to ensure every transaction and personal data is meticulously protected. Shop with absolute confidence.",
    safeFastDelivery: "Safe & Fast Delivery",
    deliveryDesc: "From our warehouse to your doorstep, every package is handled with the utmost care and dispatched swiftly. We partner with leading logistics providers to ensure your items arrive safely and on time, every time.",
    unmatchedRapidity: "Unmatched Rapidity",
    rapidityDesc: "Experience lightning-fast Browse, quick and seamless checkout processes, and immediate customer support. Our optimized platform ensures your journey from discovery to delivery is swift and efficient.",
    discoverCollections: "Discover Our Curated Collections",
    ClassicCuts: "Classic Cuts",
    ModernSilhouettes: "Modern Silhouettes",
    LimitedEditions: "Limited Editions",
    electronics: "Electronics",
    apparel: "Apparel",
    homeLiving: "Home & Living",
    readyToElevate: "Ready to Elevate Your Shopping Experience?",
    exploreBlend: "Explore our exclusive range of products and discover the perfect blend of style, innovation, and quality.",
    startShopping: "Start Shopping Today",
    allRightsReserved: "All rights reserved.",
    experienceLuxury: "Experience Luxury E-commerce.",
    productName: "Product Name",
    category: "Category",
    price: "Price",
    description: "Description",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    addProduct: "Add Product",
    saveChanges: "Save Changes",
    cancelEdit: "Cancel Edit",
    clearForm: "Clear Form",
    currentProducts: "Current Products",
    noProductsFound: "No products found in the database. Add a new one!",
    orderId: "Order ID",
    customer: "Customer",
    contact: "Contact",
    address: "Address",
    items: "Items",
    total: "Total",
    status: "Status",
    orderDate: "Order Date",
    userId: "User ID",
    updateStatus: "Update Status",
    pendingCall: "Pending Call",
    confirmed: "Confirmed",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    filterByStatus: "Filter by Status:",
    sortBy: "Sort By:",
    orderDateSort: "Order Date",
    totalAmountSort: "Total Amount",
    customerNameSort: "Customer Name",
    statusSort: "Status",
    ascending: "Ascending",
    descending: "Descending",
    loadingOrders: "Loading orders...",
    errorFetchingOrders: "Failed to fetch orders.",
    noOrdersFound: "No orders found.",
    adminDashboard: "Admin Dashboard",
    loggedInAs: "Logged in as:",
    orderManagement: "Order Management",
    productManagement: "Product Management",
    editProduct: "Edit Product",
    addNewProduct: "Add New Product",
    productNameRequired: "Product name is required.",
    descriptionRequired: "Description is required.",
    validPriceRequired: "Valid price is required.",
    imageUrlRequired: "Image URL is required.",
    categoryRequired: "Category is required.",
    failedToReadImage: "Failed to read image file.",
    currentImagePreview: "Current Image Preview:",
    saving: "Saving...",
    permissionDeniedAdmin: "Access Denied: You do not have administrator privileges to view this page.",
    currentUserUid: "Current User ID",
    ensureFirebaseRules: "Please ensure your Firebase security rules allow your UID access, or log in with an authorized account.",
    goToHome: "Go to Home Page",
    accessDenied: "Access Denied",
    quantity: "Quantity",
    addToCart: "Add to Cart",
    added: "Added! ✔",
    productNotFound: "Product not found. It might have been removed or does not exist.",
    goBackToProducts: "Go back to products",
    productSpecifications: "Product Specifications:",
    readCustomerReviews: "Read Customer Reviews",
    youMightAlsoLove: "You Might Also Love",
    backToProducts: "Back to Products",
    orderSummary: "Order Summary",
    subtotal: "Subtotal:",
    shipping: "Shipping:",
    placeOrder: "Place Order",
    shippingInformation: "Shipping Information",
    fullName: "Full Name",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    streetAddress: "Street Address",
    town: "Town",
    wilaya: "Wilaya (Province)",
    selectWilaya: "Select a Wilaya",
    emailInvalid: "Email address is invalid.",
    phoneInvalid: "Phone number is invalid (e.g., +213xxxxxxxxx).",
    noItemsCheckout: "No items selected for checkout.",
    goBackToCart: "Go to Cart",
    orderPlacedSuccess: "Order Placed! 🎉",
    thankYouOrderPlaced: "Thank you! Your order has been successfully placed.",
    failedToPlaceOrder: "Failed to place order:",
    checkoutSecurely: "Checkout securely",
    image: "Image",
    productNamePlaceholder: "e.g., Luxury Smartwatch",
    selectCategory: "Select Category",
    notSelected: "Not Selected",
    productImageURL: "Product Image (URL or Upload)",
    orUploadImage: "Alternatively, upload an image directly:",
    productPreview: "Product Preview",
    broken: "Broken",
    detailedDescriptionPlaceholder: "A detailed description of the product...",
    typeDELETEConfirmDelete: "Type 'DELETE' to confirm deletion of this product:",
    firestoreNotInitialized: "Firestore not initialized. Cannot perform action.",
    permissionDeniedOrderUpdate: "Permission Denied: Only administrators can update order status.",
    failedToUpdateStatus: "Failed to update status for order",
    permissionDeniedProductAddEdit: "Permission Denied: Only administrators can add/edit products.",
    failedToSaveProduct: "Failed to save product",
    permissionDeniedProductEdit: "Permission Denied: Only administrators can edit products.",
    permissionDeniedProductDelete: "Permission Denied: Only administrators can delete products.",
    waitingForFirebase: "Waiting for Firebase initialization...",
    error: "Error",
    checkConsoleReload: "Please check your console for more details or reload the page.",
    tryAdjustingFilters: "Try adjusting your filters or wait for new orders!",
    productsLoading: "Loading products...",
    errorLoadingProducts: "Error loading products",
    pleaseTryAgain: "Please try again.",
    ensureFirebaseConnection: "Ensure your Firebase connection is active.",
    placingOrder: "Placing Order...",
    yourCartIsEmpty: "Your cart is empty.",
    startAddingProducts: "Start adding products to your cart!",
    exploreProducts: "Explore Products",
    yourCartItems: "Your Cart Items",
    removeFromCart: "Remove from cart",
    proceedToCheckout: "Proceed to Checkout",
    clearCart: "Clear Cart",
    searchProducts: "Search Products",
    searchPlaceholder: "Search by name, category, or description...",
    filterByCategory: "Filter by Category",
    toggleSortOrder: "Toggle sort order",
    noProductsAvailable: "No products available at the moment.",
    checkBackLater: "Please check back later or add some products from the Admin page.",
    noMatchingProducts: "No matching products found.",
    tryDifferentFilters: "Try different search terms or filters.",
    imageNA: "N/A",
    hoverToZoom: "Hover to Zoom",
    login: "Login",
    password: "Password",
    adminLoginTitle: "Admin Login",
    loggingIn: "Logging In...",
    loginButton: "Login",
    logout: "Logout",
    userProfile: "User Profile",
    selectLanguage: "Select Language",
    closeMenu: "Close Menu",
    openMenu: "Open Menu",
    loginErrorGeneric: "Login failed. Please check your credentials and try again.",
    loginErrorInvalidEmail: "Invalid email format.",
    loginErrorUserNotFound: "No user found with this email.",
    loginErrorWrongPassword: "Incorrect password.",
    loginErrorInvalidCredential: "Invalid credentials. Please try again.",
    logoutSuccess: "You have been logged out.",
    logoutError: "Error logging out",
    search: "Search",
    classicCutsDesc: "Discover timeless elegance and tailored perfection.",
    modernSilhouettesDesc: "Explore contemporary designs and bold new forms.",
    limitedEditionsDesc: "Exclusive pieces, crafted for the discerning few.",
    loading3DModel: "Loading 3D Model",
    dragToRotateZoom: "Drag to rotate, scroll to zoom",
    productDetails: "Product Details",
    sizeGuide: "Size Guide",
    careInstructions: "Care Instructions",
    sizeGuideTitle: "Our Sizing Guide",
    sizeGuideDescription: "Find your perfect fit with our detailed measurements.",
    cm: "cm",
    measurementsDisclaimer: "*All measurements are approximate and may vary slightly.",
    careInstructionsTitle: "Care & Maintenance",
    dryCleanOnlyDetailed: "Dry clean only to preserve the fabric and shape.",
    doNotBleach: "Do not bleach.",
    coolIronRecommended: "Cool iron recommended, inside out.",
    avoidTumbleDry: "Do not tumble dry.",
    referToLabelForSpecifics: "Always refer to the garment's inner label for specific care instructions.",
    deliveryOptions: "Delivery Options",
    chooseWilaya: "Choose your Wilaya",
    shippingType: "Shipping Type",
    homeDelivery: "Home Delivery",
    pickupPoint: "Pickup Point",
    shippingCost: "Shipping Cost",
    totalWithShipping: "Total (with shipping)",
    selectYourWilaya: "Select your wilaya for shipping calculation",
    premiumCottonLinenBlend: "Premium Cotton Linen Blend",
    tailoredSlimFit: "Tailored Slim Fit",
    buttonZipFly: "Button & Zip Fly",
    sideSeamPocketsBackWeltPockets: "Side-seam pockets, back welt pockets",
    dryCleanOnly: "Dry Clean Only",
    craftedInItaly: "Crafted in Italy",
    yearsManufacturerWarranty: "Years Manufacturer Warranty",
    matchingPoloShirt: "Matching Polo Shirt",
    leatherBelt: "Leather Belt",
    classicSneakers: "Classic Sneakers",
    your: "Your",
    notAvailable: "N/A",
    material: "Material",
    dimensions: "Dimensions",
    highQualityAluminum: "High-Quality Aluminum",
    reviewGreatProduct: "This is a great product!",
    reviewerName: "John Doe",
    reviewHighlyRecommend: "Highly recommend to everyone.",
    anotherReviewer: "Jane Smith",
    weight: "Weight",
    warranty: "Warranty",
    // New keys from components
    selectAllItems: "Select All Items",
    cartPageTitlePart1: "Your",
    cartPageTitlePart2: "Shopping Cart",
    cartFeelsLonely: "Your cart feels a little lonely.",
    exploreCollectionsPrompt: "Why not explore our exquisite collections and find something you love?",
    startShoppingNow: "Start Shopping Now",
    remove: "Remove",
    orderSummaryTitle: "Order Summary",
    shippingInformationTitle: "Shipping Information",
    fullNameLabel: "Full Name",
    fullNamePlaceholder: "John Doe",
    emailLabel: "Email Address",
    emailPlaceholder: "john@example.com",
    phoneLabel: "Phone Number",
    phonePlaceholder: "+213XXXXXXXXX",
    addressLabel: "Street Address",
    addressPlaceholder: "123 Main Street",
    wilayaRequired: "Wilaya is required",
    townRequired: "Town is required",
    selectWilayaForShipping: "Select wilaya for shipping",
    placeOrderButton: "Place Order",
    placingOrder: "Placing Order...",
    orderPlacedSuccessButton: "Order Placed!",
    orderPlacedThankYou: "Thank you! Your order has been successfully placed.",
    noItemsSelected: "No items selected for checkout.",
    goBackToCartPrompt: "Why not go back to your cart and add some items?",
    goToCartButton: "Go to Cart",
    discoverCollection: "Discover Collection",
    theVIZOAdvantage: "The VIZO Advantage",
    experienceHassleFree: "Experience hassle-free fashion with quality and speed.",
    fastReliableShipping: "Fast & Reliable Shipping",
    shippingDesc: "Get your style delivered swiftly across all Algerian provinces.",
    curatedQuality: "Curated Quality",
    qualityDesc: "Hand-picked clothing that meets high standards for durability and style.",
    latestTrendsStyles: "Latest Trends & Styles",
    trendsDesc: "Stay ahead with a constantly updated collection of the freshest fashion.",
    hassleFreeReturns: "Hassle-Free Returns",
    returnsDesc: "Easy exchanges and returns for a worry-free shopping experience.",
    whatOurCustomersSay: "What Our Customers Say",
    realFeedback: "Real feedback from satisfied VIZO fashion lovers.",
    readyToUpgradeWardrobe: "Ready to Upgrade Your Wardrobe?",
    exploreVIZOCollection: "Explore VIZO's hand-picked collection of modern clothing and find your next signature look.",
    shopNow: "Shop The Collection",
    noOtherProductsAvailable: "No other products available at this time.",
    checkoutDirectly: "Checkout Directly",
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    viewAll: "View All",
  },
  fr: {
    // French translations (same structure as en)
    // ... (omitted for brevity, same keys as en but in French)
  },
  ar: {
    // Arabic translations (same structure as en)
    // ... (omitted for brevity, same keys as en but in Arabic)
  },
};

// Create the LanguageContext
export const LanguageContext = createContext();

// Create the LanguageProvider component
export const LanguageProvider = ({ children }) => {
  // Set Arabic as default language
  const [lang, setLang] = useState(() => {
    const storedLang = localStorage.getItem('zshop_lang');
    return storedLang && translations[storedLang] ? storedLang : 'ar';
  });

  // Effect to update document direction (RTL/LTR) and save preference
  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
    localStorage.setItem('zshop_lang', lang);
  }, [lang]);

  // Memoize context value
  const contextValue = useMemo(() => {
    const t = (key) => {
      if (translations[lang] && translations[lang][key]) {
        return translations[lang][key];
      }
      console.warn(`Missing translation for key: ${key} in language: ${lang}`);
      return key; // Return key as fallback
    };
    return { lang, setLang, t };
  }, [lang]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the language context
export const useLanguage = () => useContext(LanguageContext);