import React, { createContext, useState, useContext, useMemo, useEffect } from 'react';

const translations = {
  en: {
    home: "Home",
    products: "Products",
    admin: "Admin",
    cart: "Cart",
    welcomeTitle: "Welcome to ZShop",
    welcomeSlogan: "Your Gateway to Unrivaled Luxury and Exceptional Quality.",
    exploreCollections: "Explore Our Collections",
    whyChooseUs: "Why Choose ZShop?",
    unwaveringSecurity: "Unwavering Security",
    securityDesc: "Your peace of mind is our priority. We utilize cutting-edge encryption and robust security protocols to ensure every transaction and personal data is meticulously protected. Shop with absolute confidence.",
    safeFastDelivery: "Safe & Fast Delivery",
    deliveryDesc: "From our warehouse to your doorstep, every package is handled with the utmost care and dispatched swiftly. We partner with leading logistics providers to ensure your items arrive safely and on time, every time.",
    unmatchedRapidity: "Unmatched Rapidity",
    rapidityDesc: "Experience lightning-fast Browse, quick and seamless checkout processes, and immediate customer support. Our optimized platform ensures your journey from discovery to delivery is swift and efficient.",
    discoverCollections: "Discover Our Curated Collections",
    // --- NEW BURBERRY SHORTS CATEGORIES ---
    ClassicCuts: "Classic Cuts",
    ModernSilhouettes: "Modern Silhouettes",
    LimitedEditions: "Limited Editions",
    // --- END NEW CATEGORIES ---
    electronics: "Electronics", // Kept for other products if any
    apparel: "Apparel",         // Kept for other products if any
    homeLiving: "Home & Living", // Kept for other products if any
    readyToElevate: "Ready to Elevate Your Shopping Experience?",
    exploreBlend: "Explore our exclusive range of products and discover the perfect blend of style, innovation, and quality.",
    startShopping: "Start Shopping Today",
    allRightsReserved: "All rights reserved.",
    experienceLuxury: "Experience Luxury E-commerce.",
    productName: "Product Name",
    category: "Category",
    price: "Price",
    description: "Description",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    addProduct: "Add Product",
    saveChanges: "Save Changes",
    cancelEdit: "Cancel Edit",
    clearForm: "Clear Form",
    currentProducts: "Current Products",
    noProductsFound: "No products found in the database. Add a new one!",
    orderId: "Order ID",
    customer: "Customer",
    contact: "Contact",
    address: "Address",
    items: "Items",
    total: "Total",
    status: "Status",
    orderDate: "Order Date",
    userId: "User ID",
    updateStatus: "Update Status",
    pendingCall: "Pending Call",
    confirmed: "Confirmed",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    filterByStatus: "Filter by Status:",
    sortBy: "Sort By:",
    orderDateSort: "Order Date",
    totalAmountSort: "Total Amount",
    customerNameSort: "Customer Name",
    statusSort: "Status",
    ascending: "Ascending",
    descending: "Descending",
    loadingOrders: "Loading orders...",
    errorFetchingOrders: "Failed to fetch orders.",
    noOrdersFound: "No orders found.",
    adminDashboard: "Admin Dashboard",
    loggedInAs: "Logged in as:",
    orderManagement: "Order Management",
    productManagement: "Product Management",
    editProduct: "Edit Product",
    addNewProduct: "Add New Product",
    productNameRequired: "Product name is required.",
    descriptionRequired: "Description is required.",
    validPriceRequired: "Valid price is required.",
    imageUrlRequired: "Image URL is required.",
    categoryRequired: "Category is required.",
    failedToReadImage: "Failed to read image file.",
    currentImagePreview: "Current Image Preview:",
    saving: "Saving...",
    permissionDeniedAdmin: "Access Denied: You do not have administrator privileges to view this page.",
    currentUserUid: "Current User ID",
    ensureFirebaseRules: "Please ensure your Firebase security rules allow your UID access, or log in with an authorized account.",
    goToHome: "Go to Home Page",
    accessDenied: "Access Denied",
    quantity: "Quantity",
    addToCart: "Add to Cart",
    added: "Added! ✔",
    productNotFound: "Product not found. It might have been removed or does not exist.",
    goBackToProducts: "Go back to products",
    productSpecifications: "Product Specifications:",
    readCustomerReviews: "Read Customer Reviews",
    youMightAlsoLove: "You Might Also Love",
    backToProducts: "Back to Products",
    orderSummary: "Order Summary",
    subtotal: "Subtotal:",
    shipping: "Shipping:",
    placeOrder: "Place Order",
    shippingInformation: "Shipping Information",
    fullName: "Full Name",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    streetAddress: "Street Address",
    town: "Town",
    wilaya: "Wilaya (Province)",
    selectWilaya: "Select a Wilaya",
    emailInvalid: "Email address is invalid.",
    phoneInvalid: "Phone number is invalid (e.g., +213xxxxxxxxx).",
    noItemsCheckout: "No items selected for checkout.",
    goBackToCart: "Go to Cart",
    orderPlacedSuccess: "Order Placed! 🎉",
    thankYouOrderPlaced: "Thank you! Your order has been successfully placed.",
    failedToPlaceOrder: "Failed to place order:",
    checkoutSecurely: "Checkout securely",
    image: "Image",
    productNamePlaceholder: "e.g., Luxury Smartwatch",
    selectCategory: "Select Category",
    notSelected: "Not Selected",
    productImageURL: "Product Image (URL or Upload)",
    orUploadImage: "Alternatively, upload an image directly:",
    productPreview: "Product Preview",
    broken: "Broken",
    detailedDescriptionPlaceholder: "A detailed description of the product...",
    typeDELETEConfirmDelete: "Type 'DELETE' to confirm deletion of this product:",
    firestoreNotInitialized: "Firestore not initialized. Cannot perform action.",
    permissionDeniedOrderUpdate: "Permission Denied: Only administrators can update order status.",
    failedToUpdateStatus: "Failed to update status for order",
    permissionDeniedProductAddEdit: "Permission Denied: Only administrators can add/edit products.",
    failedToSaveProduct: "Failed to save product",
    permissionDeniedProductEdit: "Permission Denied: Only administrators can edit products.",
    permissionDeniedProductDelete: "Permission Denied: Only administrators can delete products.",
    waitingForFirebase: "Waiting for Firebase initialization...",
    error: "Error",
    checkConsoleReload: "Please check your console for more details or reload the page.",
    tryAdjustingFilters: "Try adjusting your filters or wait for new orders!",
    productsLoading: "Loading products...",
    errorLoadingProducts: "Error loading products",
    pleaseTryAgain: "Please try again.",
    ensureFirebaseConnection: "Ensure your Firebase connection is active.",
    placingOrder: "Placing Order...",
    yourCartIsEmpty: "Your cart is empty.",
    startAddingProducts: "Start adding products to your cart!",
    exploreProducts: "Explore Products",
    yourCartItems: "Your Cart Items",
    removeFromCart: "Remove from cart",
    proceedToCheckout: "Proceed to Checkout",
    clearCart: "Clear Cart",
    searchProducts: "Search Products",
    searchPlaceholder: "Search by name, category, or description...",
    filterByCategory: "Filter by Category",
    toggleSortOrder: "Toggle sort order",
    noProductsAvailable: "No products available at the moment.",
    checkBackLater: "Please check back later or add some products from the Admin page.",
    noMatchingProducts: "No matching products found.",
    tryDifferentFilters: "Try different search terms or filters.",
    imageNA: "N/A",
    hoverToZoom: "Hover to Zoom",
    login: "Login",
    password: "Password",
    adminLoginTitle: "Admin Login",
    loggingIn: "Logging In...",
    loginButton: "Login",
    logout: "Logout",
    userProfile: "User Profile",
    selectLanguage: "Select Language",
    closeMenu: "Close Menu",
    openMenu: "Open Menu",
    loginErrorGeneric: "Login failed. Please check your credentials and try again.",
    loginErrorInvalidEmail: "Invalid email format.",
    loginErrorUserNotFound: "No user found with this email.",
    loginErrorWrongPassword: "Incorrect password.",
    loginErrorInvalidCredential: "Invalid credentials. Please try again.",
    logoutSuccess: "You have been logged out.",
    logoutError: "Error logging out",
    search: "Search",
    classicCutsDesc: "Discover timeless elegance and tailored perfection.",
modernSilhouettesDesc: "Explore contemporary designs and bold new forms.",
limitedEditionsDesc: "Exclusive pieces, crafted for the discerning few.",
 loading3DModel: "Loading 3D Model",
  dragToRotateZoom: "Drag to rotate, scroll to zoom",
  productDetails: "Product Details",
  sizeGuide: "Size Guide",
  careInstructions: "Care Instructions",
  sizeGuideTitle: "Our Sizing Guide",
  sizeGuideDescription: "Find your perfect fit with our detailed measurements.",
  cm: "cm",
  measurementsDisclaimer: "*All measurements are approximate and may vary slightly.",
  careInstructionsTitle: "Care & Maintenance",
  dryCleanOnlyDetailed: "Dry clean only to preserve the fabric and shape.",
  doNotBleach: "Do not bleach.",
  coolIronRecommended: "Cool iron recommended, inside out.",
  avoidTumbleDry: "Do not tumble dry.",
  referToLabelForSpecifics: "Always refer to the garment's inner label for specific care instructions.",
  subtotal: "Subtotal",
  deliveryOptions: "Delivery Options",
  selectWilaya: "Select Wilaya",
  chooseWilaya: "Choose your Wilaya",
  shippingType: "Shipping Type",
  homeDelivery: "Home Delivery",
  pickupPoint: "Pickup Point",
  shippingCost: "Shipping Cost",
  totalWithShipping: "Total (with shipping)",
  selectYourWilaya: "Select your wilaya for shipping calculation",
  premiumCottonLinenBlend: "Premium Cotton Linen Blend",
  tailoredSlimFit: "Tailored Slim Fit",
  buttonZipFly: "Button & Zip Fly",
  sideSeamPocketsBackWeltPockets: "Side-seam pockets, back welt pockets",
  dryCleanOnly: "Dry Clean Only",
  craftedInItaly: "Crafted in Italy",
  yearsManufacturerWarranty: "Years Manufacturer Warranty",
  matchingPoloShirt: "Matching Polo Shirt",
  leatherBelt: "Leather Belt",
  classicSneakers: "Classic Sneakers",
    your: "Your",
    notAvailable: "N/A",
    material: "Material",
    dimensions: "Dimensions",
    highQualityAluminum: "High-Quality Aluminum",
    reviewGreatProduct: "This is a great product!",
    reviewerName: "John Doe",
    reviewHighlyRecommend: "Highly recommend to everyone.",
    anotherReviewer: "Jane Smith",
    weight: "Weight",
    warranty: "Warranty",
  },
  fr: {
    home: "Accueil",
    products: "Produits",
    admin: "Admin",
    cart: "Panier",
    welcomeTitle: "Bienvenue chez ZShop",
    welcomeSlogan: "Votre porte d'entrée vers un luxe inégalé et une qualité exceptionnelle.",
    exploreCollections: "Explorer Nos Collections",
    whyChooseUs: "Pourquoi Choisir ZShop ?",
    unwaveringSecurity: "Sécurité Inébranlable",
    securityDesc: "Votre tranquillité d'esprit est notre priorité. Nous utilisons un cryptage de pointe et des protocoles de sécurité robustes pour garantir que chaque transaction et donnée personnelle sont méticuleusement protégées. Achetez en toute confiance.",
    safeFastDelivery: "Livraison Sûre & Rapide",
    deliveryDesc: "De notre entrepôt à votre porte, chaque colis est traité avec le plus grand soin et expédié rapidement. Nous travaillons avec des prestataires logistiques de premier plan pour garantir que vos articles arrivent en toute sécurité et à temps, à chaque fois.",
    unmatchedRapidity: "Rapidité Inégalée",
    rapidityDesc: "Profitez d'une navigation ultra-rapide, de processus de paiement fluides et d'un support client immédiat. Notre plateforme optimisée garantit que votre parcours, de la découverte à la livraison, est rapide et efficace.",
    discoverCollections: "Découvrez Nos Collections Sélectionnées",
    // --- NEW BURBERRY SHORTS CATEGORIES ---
    ClassicCuts: "Coupes Classiques",
    ModernSilhouettes: "Silhouettes Modernes",
    LimitedEditions: "Éditions Limitées",
    // --- END NEW CATEGORIES ---
    electronics: "Électronique",
    apparel: "Vêtements",
    homeLiving: "Maison & Vie",
    readyToElevate: "Prêt(e) à Améliorer Votre Expérience d'Achat ?",
    exploreBlend: "Explorez notre gamme exclusive de produits et découvrez le mélange parfait de style, d'innovation et de qualité.",
    startShopping: "Commencer à Acheter Aujourd'hui",
    allRightsReserved: "Tous droits réservés.",
    experienceLuxury: "Découvrez le luxe du commerce électronique.",
    productName: "Nom du produit",
    category: "Catégorie",
    price: "Prix",
    description: "Description",
    actions: "Actions",
    edit: "Modifier",
    delete: "Supprimer",
    addProduct: "Ajouter un produit",
    saveChanges: "Enregistrer les modifications",
    cancelEdit: "Annuler la modification",
    clearForm: "Effacer le formulaire",
    currentProducts: "Produits Actuels",
    noProductsFound: "Aucun produit trouvé dans la base de données. Ajoutez-en un nouveau !",
    orderId: "ID Commande",
    customer: "Client",
    contact: "Contact",
    address: "Adresse",
    items: "Articles",
    total: "Total",
    status: "Statut",
    orderDate: "Date Commande",
    userId: "ID Utilisateur",
    updateStatus: "Mettre à jour le statut",
    pendingCall: "Appel en attente",
    confirmed: "Confirmé",
    shipped: "Expédié",
    delivered: "Livré",
    cancelled: "Annulé",
    filterByStatus: "Filtrer par statut :",
    sortBy: "Trier par :",
    orderDateSort: "Date de commande",
    totalAmountSort: "Montant total",
    customerNameSort: "Nom du client",
    statusSort: "Statut",
    ascending: "Croissant",
    descending: "Décroissant",
    loadingOrders: "Chargement des commandes...",
    errorFetchingOrders: "Échec de la récupération des commandes.",
    noOrdersFound: "Aucune commande trouvée.",
    adminDashboard: "Tableau de bord Admin",
    loggedInAs: "Connecté en tant que :",
    orderManagement: "Gestion des commandes",
    productManagement: "Gestion des produits",
    editProduct: "Modifier le produit",
    addNewProduct: "Ajouter un nouveau produit",
    productNameRequired: "Le nom du produit est requis.",
    descriptionRequired: "La description est requise.",
    validPriceRequired: "Un prix valide est requis.",
    imageUrlRequired: "L'URL de l'image est requise.",
    categoryRequired: "La catégorie est requise.",
    failedToReadImage: "Échec de la lecture du fichier image.",
    currentImagePreview: "Aperçu de l'image actuelle :",
    saving: "Enregistrement...",
    permissionDeniedAdmin: "Accès refusé : Vous n'avez pas les privilèges d'administrateur pour afficher cette page.",
    currentUserUid: "ID Utilisateur Actuel :",
    ensureFirebaseRules: "Veuillez vous assurer que vos règles de sécurité Firebase autorisent l'accès à votre UID, ou connectez-vous avec un compte autorisé.",
    goToHome: "Aller à la page d'accueil",
    accessDenied: "Accès refusé",
    quantity: "Quantité",
    addToCart: "Ajouter au panier",
    added: "Ajouté ! ✔",
    productNotFound: "Produit non trouvé. Il a peut-être été supprimé ou n'existe pas.",
    goBackToProducts: "Retour aux produits",
    productSpecifications: "Spécifications du produit :",
    readCustomerReviews: "Lire les avis des clients",
    youMightAlsoLove: "Vous pourriez aussi aimer",
    backToProducts: "Retour aux produits",
    orderSummary: "Récapitulatif de la commande",
    subtotal: "Sous-total :",
    shipping: "Livraison :",
    placeOrder: "Passer la commande",
    shippingInformation: "Informations de livraison",
    fullName: "Nom complet",
    emailAddress: "Adresse e-mail",
    phoneNumber: "Numéro de téléphone",
    streetAddress: "Adresse",
    town: "Ville",
    wilaya: "Wilaya (Province)",
    selectWilaya: "Sélectionnez une Wilaya",
    emailInvalid: "L'adresse e-mail est invalide.",
    phoneInvalid: "Le numéro de téléphone est invalide (ex: +213xxxxxxxxx).",
    noItemsCheckout: "Aucun article sélectionné pour la commande.",
    goBackToCart: "Aller au panier",
    orderPlacedSuccess: "Commande passée ! 🎉",
    thankYouOrderPlaced: "Merci ! Votre commande a été passée avec succès.",
    failedToPlaceOrder: "Échec de la commande :",
    checkoutSecurely: "Paiement sécurisé",
    image: "Image",
    productNamePlaceholder: "Ex: Montre connectée de luxe",
    selectCategory: "Sélectionner une catégorie",
    notSelected: "Non sélectionné",
    productImageURL: "Image du produit (URL ou Téléchargement)",
    orUploadImage: "Alternativement, téléchargez une image directement :",
    productPreview: "Aperçu du produit",
    broken: "Cassé",
    detailedDescriptionPlaceholder: "Une description détaillée du produit...",
    typeDELETEConfirmDelete: "Tapez 'DELETE' pour confirmer la suppression de ce produit :",
    firestoreNotInitialized: "Firestore non initialisé. Impossible d'effectuer l'action.",
    permissionDeniedOrderUpdate: "Accès refusé : Seuls les administrateurs peuvent mettre à jour le statut des commandes.",
    failedToUpdateStatus: "Échec de la mise à jour du statut pour la commande",
    permissionDeniedProductAddEdit: "Accès refusé : Seuls les administrateurs peuvent ajouter/modifier des produits.",
    failedToSaveProduct: "Échec de l'enregistrement du produit",
    permissionDeniedProductEdit: "Accès refusé : Seuls les administrateurs peuvent modifier les produits.",
    permissionDeniedProductDelete: "Accès refusé : Seuls les administrateurs peuvent supprimer des produits.",
    waitingForFirebase: "En attente de l'initialisation de Firebase...",
    error: "Erreur",
    checkConsoleReload: "Veuillez vérifier votre console pour plus de détails ou recharger la page.",
    tryAdjustingFilters: "Essayez d'ajuster vos filtres ou attendez de nouvelles commandes !",
    productsLoading: "Chargement des produits...",
    errorLoadingProducts: "Erreur lors du chargement des produits",
    pleaseTryAgain: "Veuillez réessayer.",
    ensureFirebaseConnection: "Assurez-vous que votre connexion Firebase est active.",
    placingOrder: "Commande en cours...",
    yourCartIsEmpty: "Votre panier est vide.",
    startAddingProducts: "Commencez à ajouter des produits à votre panier !",
    exploreProducts: "Explorer les produits",
    yourCartItems: "Vos articles du panier",
    removeFromCart: "Retirer du panier",
    proceedToCheckout: "Passer à la caisse",
    clearCart: "Vider le panier",
    searchProducts: "Rechercher des produits",
    searchPlaceholder: "Rechercher par nom, catégorie ou description...",
    filterByCategory: "Filtrer par catégorie",
    toggleSortOrder: "Inverser l'ordre de tri",
    noProductsAvailable: "Aucun produit disponible pour le moment.",
    checkBackLater: "Veuillez revenir plus tard ou ajouter des produits depuis la page Admin.",
    noMatchingProducts: "Aucun produit correspondant trouvé.",
    tryDifferentFilters: "Essayez d'autres termes de recherche ou filtres.",
    imageNA: "N/A",
    hoverToZoom: "Survoler pour zoomer",
    login: "Connexion",
    password: "Mot de passe",
    adminLoginTitle: "Connexion Admin",
    loggingIn: "Connexion en cours...",
    loginButton: "Se connecter",
    logout: "Déconnexion",
    userProfile: "Profil Utilisateur",
    selectLanguage: "Sélectionner la langue",
    closeMenu: "Fermer le menu",
    openMenu: "Ouvrir le menu",
    loginErrorGeneric: "Échec de la connexion. Veuillez vérifier vos identifiants et réessayer.",
    loginErrorInvalidEmail: "Format d'e-mail invalide.",
    loginErrorUserNotFound: "Aucun utilisateur trouvé avec cet e-mail.",
    loginErrorWrongPassword: "Mot de passe incorrect.",
    loginErrorInvalidCredential: "Identifiants invalides. Veuillez réessayer.",
    logoutSuccess: "Vous avez été déconnecté(e).",
    logoutError: "Erreur lors de la déconnexion",
    search: "Recherche",
    your: "Votre",
    notAvailable: "N/A",
    material: "Matériau",
    dimensions: "Dimensions",
    highQualityAluminum: "Aluminium de haute qualité",
    reviewGreatProduct: "C'est un excellent produit !",
    reviewerName: "John Doe",
    reviewHighlyRecommend: "Fortement recommandé à tous.",
    anotherReviewer: "Jane Smith",
    weight: "Poids",
    warranty: "Garantie",
  },
  ar: {
    home: "الرئيسية",
    products: "المنتجات",
    admin: "المسؤول",
    cart: "السلة",
    welcomeTitle: "مرحباً بكم في ZShop",
    welcomeSlogan: "بوابتكم إلى الرفاهية التي لا تضاهى والجودة الاستثنائية.",
    exploreCollections: "اكتشف مجموعاتنا",
    whyChooseUs: "لماذا تختار ZShop؟",
    unwaveringSecurity: "أمان لا يتزعزع",
    securityDesc: "راحة بالك هي أولويتنا. نستخدم أحدث التشفير وبروتوكولات الأمان القوية لضمان حماية كل معاملة وبيانات شخصية بدقة. تسوق بثقة تامة.",
    safeFastDelivery: "توصيل آمن وسريع",
    deliveryDesc: "من مستودعاتنا إلى باب منزلك، يتم التعامل مع كل طرد بأقصى دراية وإرساله بسرعة. نحن نتعاون مع مزودي الخدمات اللوجستية الرائدين لضمان وصول أغراضك بأمان وفي الوقت المحدد، في كل مرة.",
    unmatchedRapidity: "سرعة لا تضاهى",
    rapidityDesc: "اختبر تصفحًا فائق السرعة، وعمليات دفع سلسة وسريعة، ودعم عملاء فوري. تضمن منصتنا المحسّنة أن رحلتك من الاكتشاف إلى التسليم سريعة وفعالة.",
    discoverCollections: "اكتشف مجموعاتنا المنسقة",
    // --- NEW BURBERRY SHORTS CATEGORIES ---
    ClassicCuts: "قصات كلاسيكية",
    ModernSilhouettes: "تصاميم عصرية",
    LimitedEditions: "إصدارات محدودة",
    // --- END NEW CATEGORIES ---
    electronics: "إلكترونيات",
    apparel: "ملابس",
    homeLiving: "المنزل والمعيشة",
    readyToElevate: "هل أنت مستعد لترقية تجربة التسوق الخاصة بك؟",
    exploreBlend: "استكشف مجموعتنا الحصرية من المنتجات واكتشف المزيج المثالي من الأناقة والابتكار والجودة.",
    startShopping: "ابدأ التسوق اليوم",
    allRightsReserved: "جميع الحقوق محفوظة.",
    experienceLuxury: "تجربة التجارة الإلكترونية الفاخرة.",
    productName: "اسم المنتج",
    category: "الفئة",
    price: "السعر",
    description: "الوصف",
    actions: "الإجراءات",
    edit: "تعديل",
    delete: "حذف",
    addProduct: "إضافة منتج",
    saveChanges: "حفظ التغييرات",
    cancelEdit: "إلغاء التعديل",
    clearForm: "مسح النموذج",
    currentProducts: "المنتجات الحالية",
    noProductsFound: "لم يتم العثور على منتجات في قاعدة البيانات. أضف منتجًا جديدًا!",
    orderId: "معرف الطلب",
    customer: "العميل",
    contact: "الاتصال",
    address: "العنوان",
    items: "العناصر",
    total: "الإجمالي",
    status: "الحالة",
    orderDate: "تاريخ الطلب",
    userId: "معرف المستخدم",
    updateStatus: "تحديث الحالة",
    pendingCall: "مكالمة معلقة",
    confirmed: "تم التأكيد",
    shipped: "تم الشحن",
    delivered: "تم التسليم",
    cancelled: "ملغى",
    filterByStatus: "تصفية حسب الحالة:",
    sortBy: "ترتيب حسب:",
    orderDateSort: "تاريخ الطلب",
    totalAmountSort: "المبلغ الإجمالي",
    customerNameSort: "اسم العميل",
    statusSort: "الحالة",
    ascending: "تصاعدي",
    descending: "تنازلي",
    loadingOrders: "جاري تحميل الطلبات...",
    errorFetchingOrders: "فشل في جلب الطلبات.",
    noOrdersFound: "لم يتم العثور على طلبات.",
    adminDashboard: "لوحة تحكم المسؤول",
    loggedInAs: "تم تسجيل الدخول باسم:",
    orderManagement: "إدارة الطلبات",
    productManagement: "إدارة المنتجات",
    editProduct: "تعديل المنتج",
    addNewProduct: "إضافة منتج جديد",
    productNameRequired: "اسم المنتج مطلوب.",
    descriptionRequired: "الوصف مطلوب.",
    validPriceRequired: "سعر صحيح مطلوب.",
    imageUrlRequired: "رابط الصورة مطلوب.",
    categoryRequired: "الفئة مطلوبة.",
    failedToReadImage: "فشل في قراءة ملف الصورة.",
    currentImagePreview: "معاينة الصورة الحالية:",
    saving: "جاري الحفظ...",
    permissionDeniedAdmin: "تم رفض الوصول: ليس لديك صلاحيات المسؤول لعرض هذه الصفحة.",
    currentUserUid: "معرف المستخدم الحالي:",
    ensureFirebaseRules: "يرجى التأكد من أن قواعد أمان Firebase تسمح لمعرف المستخدم الخاص بك بالوصول، أو تسجيل الدخول بحساب مصرح به.",
    goToHome: "الذهاب إلى الصفحة الرئيسية",
    accessDenied: "تم رفض الوصول",
    quantity: "الكمية",
    addToCart: "أضف إلى السلة",
    added: "تمت الإضافة! ✔",
    productNotFound: "المنتج غير موجود. قد يكون قد تم حذفه أو لا وجود له.",
    goBackToProducts: "العودة إلى المنتجات",
    productSpecifications: "مواصفات المنتج:",
    readCustomerReviews: "قراءة مراجعات العملاء",
    youMightAlsoLove: "قد يعجبك أيضًا",
    backToProducts: "العودة إلى المنتجات",
    orderSummary: "ملخص الطلب",
    subtotal: "المجموع الفرعي:",
    shipping: "الشحن:",
    placeOrder: "قدم الطلب",
    shippingInformation: "معلومات الشحن",
    fullName: "الاسم الكامل",
    emailAddress: "عنوان البريد الإلكتروني",
    phoneNumber: "رقم الهاتف",
    streetAddress: "عنوان الشارع",
    town: "المدينة",
    wilaya: "الولاية",
    selectWilaya: "اختر ولاية",
    emailInvalid: "عنوان البريد الإلكتروني غير صالح.",
    phoneInvalid: "رقم الهاتف غير صالح (مثال: +213xxxxxxxxx).",
    noItemsCheckout: "لم يتم تحديد عناصر للدفع.",
    goBackToCart: "العودة إلى السلة",
    orderPlacedSuccess: "تم تقديم الطلب! 🎉",
    thankYouOrderPlaced: "شكرا لك! تم تقديم طلبك بنجاح.",
    failedToPlaceOrder: "فشل في تقديم الطلب:",
    checkoutSecurely: "الدفع بأمان",
    image: "صورة",
    productNamePlaceholder: "مثال: ساعة ذكية فاخرة",
    selectCategory: "اختر فئة",
    notSelected: "لم يتم الاختيار",
    productImageURL: "صورة المنتج (رابط أو تحميل)",
    orUploadImage: "أو قم بتحميل صورة مباشرة:",
    productPreview: "معاينة المنتج",
    broken: "معطل",
    detailedDescriptionPlaceholder: "وصف مفصل للمنتج...",
    typeDELETEConfirmDelete: "اكتب 'DELETE' لتأكيد حذف هذا المنتج:",
    firestoreNotInitialized: "لم يتم تهيئة Firestore. لا يمكن تنفيذ الإجراء.",
    permissionDeniedOrderUpdate: "تم رفض الإذن: يمكن للمسؤولين فقط تحديث حالة الطلب.",
    failedToUpdateStatus: "فشل تحديث حالة الطلب",
    permissionDeniedProductAddEdit: "تم رفض الإذن: يمكن للمسؤولين فقط إضافة/تعديل المنتجات.",
    failedToSaveProduct: "فشل حفظ المنتج",
    permissionDeniedProductEdit: "تم رفض الإذن: يمكن للمسؤولين فقط تعديل المنتجات.",
    permissionDeniedProductDelete: "تم رفض الإذن: يمكن للمسؤولين فقط حذف المنتجات.",
    waitingForFirebase: "في انتظار تهيئة Firebase...",
    error: "خطأ",
    checkConsoleReload: "يرجى التحقق من وحدة التحكم لمزيد من التفاصيل أو إعادة تحميل الصفحة.",
    tryAdjustingFilters: "حاول تعديل عوامل التصفية أو انتظر طلبات جديدة!",
    productsLoading: "جاري تحميل المنتجات...",
    errorLoadingProducts: "خطأ في تحميل المنتجات",
    pleaseTryAgain: "الرجاء المحاولة مرة أخرى.",
    ensureFirebaseConnection: "تأكد من أن اتصالك بـ Firebase نشط.",
    placingOrder: "جاري تقديم الطلب...",
    yourCartIsEmpty: "سلتك فارغة.",
    startAddingProducts: "ابدأ بإضافة المنتجات إلى سلتك!",
    exploreProducts: "استكشاف المنتجات",
    yourCartItems: "عناصر سلتك",
    removeFromCart: "إزالة من السلة",
    proceedToCheckout: "المتابعة إلى الدفع",
    clearCart: "مسح السلة",
    searchProducts: "البحث عن المنتجات",
    searchPlaceholder: "ابحث بالاسم، الفئة، أو الوصف...",
    filterByCategory: "تصفية حسب الفئة",
    toggleSortOrder: "تبديل ترتيب الفرز",
    noProductsAvailable: "لا توجد منتجات متاحة حاليا.",
    checkBackLater: "يرجى التحقق لاحقًا أو إضافة بعض المنتجات من صفحة المسؤول.",
    noMatchingProducts: "لم يتم العثور على منتجات مطابقة.",
    tryDifferentFilters: "حاول استخدام مصطلحات بحث أو عوامل تصفية مختلفة.",
    imageNA: "غير متاح",
    hoverToZoom: "مرر للتكبير",
    login: "تسجيل الدخول",
    password: "كلمة المرور",
    adminLoginTitle: "تسجيل دخول المسؤول",
    loggingIn: "جاري تسجيل الدخول...",
    loginButton: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    userProfile: "ملف المستخدم",
    selectLanguage: "اختيار اللغة",
    closeMenu: "إغلاق القائمة",
    openMenu: "فتح القائمة",
    loginErrorGeneric: "فشل تسجيل الدخول. يرجى التحقق من بيانات الاعتماد والمحاولة مرة أخرى.",
    loginErrorInvalidEmail: "صيغة البريد الإلكتروني غير صالحة.",
    loginErrorUserNotFound: "لم يتم العثور على مستخدم بهذا البريد الإلكتروني.",
    loginErrorWrongPassword: "كلمة مرور خاطئة.",
    loginErrorInvalidCredential: "بيانات اعتماد غير صالحة. الرجاء المحاولة مرة أخرى.",
    logoutSuccess: "تم تسجيل خروجك بنجاح.",
    logoutError: "خطأ في تسجيل الخروج",
    search: "بحث",
    your: "سلتك",
    notAvailable: "غير متاح",
    material: "المادة",
    dimensions: "الأبعاد",
    highQualityAluminum: "ألومنيوم عالي الجودة",
    reviewGreatProduct: "هذا منتج رائع!",
    reviewerName: "جون دو",
    reviewHighlyRecommend: "نوصي به بشدة للجميع.",
    anotherReviewer: "جين سميث",
    weight: "الوزن",
    warranty: "الضمان",
  },
};

// Create the LanguageContext
export const LanguageContext = createContext();

// Create the LanguageProvider component
export const LanguageProvider = ({ children }) => {
  // Get preferred language from localStorage or default to 'en'
  const [lang, setLang] = useState(() => {
    const storedLang = localStorage.getItem('zshop_lang');
    return storedLang && translations[storedLang] ? storedLang : 'en';
  });

  // Effect to update document direction (RTL/LTR) and save preference
  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang; // Set HTML lang attribute
    localStorage.setItem('zshop_lang', lang);
  }, [lang]);

  // Memoize the 't' (translate) function and the 'currentLang' object
  // This prevents unnecessary re-renders for consumers of the context.
  const contextValue = useMemo(() => {
    // 't' function: takes a key and returns the translated string
    const t = (key) => translations[lang][key] || key; // Fallback to key if translation missing
    return { lang, setLang, t };
  }, [lang]); // Recalculate if 'lang' changes

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the language context
export const useLanguage = () => useContext(LanguageContext);